# Use official Python image as a base
FROM python:3.10

# Set the working director

RUN pip install rpcudp filelock rpyc
RUN apt-get update && apt-get install -y iproute2
# Expose ports for the nodes
