# Use official Python image as a base
FROM base-image:latest

# Set the working directory
WORKDIR /app

# Copy files into the container
COPY testNodes.py /app/
COPY kademlia /app/kademlia
COPY server.sh /app/ 

# Ensure the script has execution permissions
RUN chmod +x /app/server.sh


# Expose ports for the nodes
EXPOSE 8468-8499

# Command to run the node (arguments are provided at runtime)
ENTRYPOINT ["/bin/sh", "-c", "/app/server.sh $@ && exec python testNodes.py $@ "]